introduction/urls.py
from django.urls import path
from . import views

app_name='introduction'
urlpatterns = [
    path('', views.profile, name="profile"),
    
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import introduction.urls
import posts.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('', views.main, name="main"),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from .views import *
app_name="posts"

urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('show/<int:id>/', show, name="show"),
]

introduction/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    Content = models.TextField()
    view_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

introduction/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'introduction/profile.html')

myblog/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

posts/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.
def new(request):
    return render(request, 'posts/new.html')

def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        Post.objects.create(title=title, Content=content)
    return redirect('posts:main')

def main(request):
    posts = Post.objects.all()
    return render(request,'posts/main.html', {'posts': posts})

def show(request, id):
    post = Post.objects.get(pk=id)
    return render(request, 'posts/show.html', {'post':post})

introduction/templates/introduction/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>자기소개 페이지</h1>

{% endblock %}

myblog/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <title>My Blog</title>
  </head>
  <body>
    {% include 'shared/_navbar.html' %}
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>메인 페이지</h1>
<img src="{% static 'image/3.PNG' %}">
{% endblock %}

myblog/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">Myblog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'introduction:profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}">글 목록</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>

posts/templates/posts/main.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
<div class="container">
    <h1>글 목록입니다.</h1>
    <a href="{% url 'posts:new' %}" class="btn btn-primary">새글쓰기</a>
    <div class="row"> 
        {% for post in posts %} 
        <div class="col-md-4 col-12"> 
            <div class="card" style="width: 18rem; margin-top: 20px;"> 
                <div class="card-body"> 
                    <h5 class="card-title">{{ post.title }}</h5> 
                    <p class="card-text">{{ post.content }}</p> 
                    <p>{{ post.created_at }}</p> 
                    <a href="{% url 'posts:show' post.pk %}" class="btn btn-primary">상세보기</a> 
                </div> 
            </div>
        </div> 
        {% endfor %} 
    </div> 
</div> {% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %} 
{% block content %} 
<div class="container"> 
    <h1> 
        새로운 글 작성하기 
    </h1> 
    <form action="{% url 'posts:create' %}" method="POST">
        {% csrf_token %} 
        <div class="form-group"> 
            <label>글 제목</label> 
            <input type="text" class="form-control" name="title"> 
        </div> 
        <div class="form-group"> 
            <label>글 내용</label> 
            <textarea class="form-control" name="content"></textarea> 
        </div>
        <input type="submit" value="글 작성" class="btn btn-outline-primary"> 
    </form>   
</div> 
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content %}

<h1>상세보기 페이지</h1>
<h3>글 제목: {{ post.title }}</h3><br>
<h3>글 내용: {{ post.Content }}</h3><br>
<h3>작성 시각: {{ post.created_at }}</h3><br>
{% endblock %}